### ISSUE TITLE
[Request] Refactor to remove Function()

### ISSUE THREAD

**Issue by moderndeveloperllc** [vaadin/vaadin-development-mode-detector#29]
Currently this line:
https://github.com/vaadin/vaadin-development-mode-detector/blob/ef8b5535d3eae1da4ffda8b02215c2640d647693/vaadin-development-mode-detector.html#L68
will trigger a CSP report if `unsafe-eval` is not enabled. Unfortunately, this is probably the most dangerous thing to enable.

Could thought be put into how the same functionality could be achieved without having `eval()`'ed code?

**Comment by web-padawan** [comment]
Thanks for the issue. Please keep in mind that code relying on that `eval` is only needed for development mode (localhost), and is not supposed to be used in production mode at all. 

Any code passed to `uncommentAndRun` is wrapped in a JS comment, so in production that code (usage statistics or license checker) will be stripped by JS minification step.

Of course, we understand the importance of CSP - and in particular, the fact that some projects also use CSP enabled in development (those will not get license checker, for example).

Is it so that `try` .. `catch` block is not enough to silently fail with CSP enabled?

**Comment by moderndeveloperllc** [comment]
@web-padawan Sorry. Looks like the issue was actually that webpack was including a global shim with `Function()`. Adding the workaround at found in one of the last comments [here](https://github.com/webpack/webpack/issues/6461) was the workaround. I'll close.
